version: "3"
# List down all the services here
services:
  server:
    container_name: "tax-system"
    ports:
      - 3000:3000
    build:
      context: .
    entrypoint: ""
    command: sh -c "yarn start && yarn test"
    # command: /usr/src/app/init.sh
    working_dir: /app
    volumes:
      - .:/app
